// Code generated by goyacc -o ./yacc.go ./turtle.y. DO NOT EDIT.

//line ./turtle.y:2
package turtle

import __yyfmt__ "fmt"

//line ./turtle.y:2

import (
	"fmt"
	"github.com/maartyman/rdfgo/interfaces"
	. "github.com/maartyman/rdfgo/lib/data_model"
	"strings"
)

type predicateObject struct {
	Predicate interfaces.ITerm
	Object    interfaces.ITerm
}

//line ./turtle.y:17
type yySymType struct {
	yys     int
	term    interfaces.ITerm
	literal interfaces.ILiteral
	str     string
	quad    interfaces.IQuad
	predObj struct {
		pairs []predicateObject
	}
	blankNodePO struct {
		node    interfaces.IBlankNode
		triples []interfaces.IQuad
	}
	objectList []interfaces.ITerm
}

const _NUMBER = 57346
const _PNAME = 57347
const _PVALUE = 57348
const _BNODE = 57349
const _NNODE = 57350
const _LITERAL = 57351
const _LANGTAG = 57352
const _DATATYPE = 57353
const _SPARQLPREFIX = 57354
const _SPARQLBASE = 57355
const _DOT = 57356
const _SEMICOLON = 57357
const _COMMA = 57358
const _PREFIX = 57359
const _BASE = 57360
const _ERROR = 57361
const _A = 57362
const _BRACKETOPEN = 57363
const _BRACKETCLOSE = 57364
const _TRUE = 57365
const _FALSE = 57366
const _LPAREN = 57367
const _RPAREN = 57368

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"_NUMBER",
	"_PNAME",
	"_PVALUE",
	"_BNODE",
	"_NNODE",
	"_LITERAL",
	"_LANGTAG",
	"_DATATYPE",
	"_SPARQLPREFIX",
	"_SPARQLBASE",
	"_DOT",
	"_SEMICOLON",
	"_COMMA",
	"_PREFIX",
	"_BASE",
	"_ERROR",
	"_A",
	"_BRACKETOPEN",
	"_BRACKETCLOSE",
	"_TRUE",
	"_FALSE",
	"_LPAREN",
	"_RPAREN",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line ./turtle.y:277

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 91

var yyAct = [...]int8{
	35, 49, 21, 36, 47, 12, 38, 34, 14, 55,
	23, 54, 61, 24, 48, 23, 45, 17, 24, 37,
	16, 44, 62, 50, 17, 45, 17, 16, 37, 16,
	44, 53, 46, 11, 19, 42, 43, 18, 33, 25,
	52, 30, 11, 56, 42, 43, 18, 57, 58, 51,
	29, 59, 23, 60, 28, 24, 20, 32, 17, 27,
	13, 16, 50, 64, 63, 7, 10, 26, 31, 17,
	8, 9, 16, 17, 11, 41, 16, 15, 18, 48,
	40, 4, 5, 3, 25, 2, 1, 39, 25, 22,
	6,
}

var yyPact = [...]int16{
	-1000, 53, -1000, -1000, -1000, 20, 68, 62, 54, 46,
	42, 19, -1000, -1000, -1000, -1000, -1000, 51, 12, -1000,
	18, -1, 21, -1000, -1000, -1000, 41, 32, 17, -1000,
	-1000, -11, -1000, -1000, -17, 21, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 37, -1000, -1000, -1000, 64, -1000,
	-4, -1000, 8, -1000, -1000, -1000, -1000, -1000, -1000, -1,
	-1000, 21, -1000, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 90, 0, 6, 89, 3, 56, 1, 4, 2,
	80, 75, 87, 7, 86, 85, 83, 81,
}

var yyR1 = [...]int8{
	0, 14, 14, 15, 15, 17, 17, 17, 17, 16,
	16, 6, 9, 8, 8, 8, 4, 4, 4, 7,
	7, 11, 11, 13, 13, 1, 1, 1, 1, 1,
	2, 2, 2, 2, 2, 2, 12, 12, 12, 12,
	12, 12, 10, 10, 3, 3, 5,
}

var yyR2 = [...]int8{
	0, 0, 2, 1, 1, 3, 4, 3, 2, 2,
	3, 2, 2, 0, 3, 2, 1, 1, 1, 1,
	3, 2, 3, 1, 2, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
	2, 1, 2, 3, 2, 1, 1,
}

var yyChk = [...]int16{
	-1000, -14, -15, -16, -17, -10, -1, 12, 17, 18,
	13, 21, -5, 7, -3, -11, 8, 5, 25, 14,
	-6, -9, -4, -5, -3, 20, 5, 5, 8, 8,
	22, -6, 6, 26, -13, -2, -5, 7, -3, -12,
	-10, -11, 23, 24, 9, 4, 14, -8, 15, -7,
	-2, 8, 8, 14, 22, 26, -13, 10, 11, -9,
	-8, 16, 14, -8, -7,
}

var yyDef = [...]int8{
	1, -2, 2, 3, 4, 28, 0, 0, 0, 0,
	0, 0, 25, 26, 27, 29, 46, 45, 0, 9,
	0, 13, 0, 16, 17, 18, 0, 0, 0, 8,
	42, 0, 44, 21, 0, 23, 30, 31, 32, 33,
	34, 35, 36, 37, 38, 41, 10, 11, 13, 12,
	19, 5, 0, 7, 43, 22, 24, 39, 40, 13,
	15, 0, 6, 14, 20,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./turtle.y:55
		{
			yylex.(*lexer).prefixes[yyDollar[2].str] = yyDollar[3].str
		}
	case 6:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./turtle.y:58
		{
			yylex.(*lexer).prefixes[yyDollar[2].str] = yyDollar[3].str
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./turtle.y:61
		{
			yylex.(*lexer).base = yyDollar[2].str
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./turtle.y:64
		{
			yylex.(*lexer).base = yyDollar[2].str
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./turtle.y:70
		{
			for _, q := range yyDollar[1].blankNodePO.triples {
				yylex.(*lexer).output <- q
			}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./turtle.y:75
		{
			for _, po := range yyDollar[2].predObj.pairs {
				quad, err := NewQuad(yyDollar[1].term, po.Predicate, po.Object, NewDefaultGraph())
				if err != nil {
					yylex.(*lexer).Error(fmt.Sprintf("error constructing quad: %v", err))
					return 1
				}
				yylex.(*lexer).output <- quad
			}
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./turtle.y:88
		{
			yyVAL.predObj = yyDollar[1].predObj
			yyVAL.predObj.pairs = append(yyVAL.predObj.pairs, yyDollar[2].predObj.pairs...)
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./turtle.y:95
		{
			yyVAL.predObj = yyDollar[2].predObj
			for i := range yyVAL.predObj.pairs {
				yyVAL.predObj.pairs[i].Predicate = yyDollar[1].term
			}
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./turtle.y:104
		{
			yyVAL.predObj.pairs = []predicateObject{}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./turtle.y:107
		{
			yyVAL.predObj = yyDollar[2].predObj
			yyVAL.predObj.pairs = append(yyVAL.predObj.pairs, yyDollar[3].predObj.pairs...)
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./turtle.y:111
		{
			yyVAL.predObj = yyDollar[2].predObj
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:117
		{
			yyVAL.term = yyDollar[1].term
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:118
		{
			yyVAL.term = yyDollar[1].term
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:119
		{
			yyVAL.term = IRI.RDF.Type
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:122
		{
			yyVAL.predObj.pairs = []predicateObject{{Predicate: nil, Object: yyDollar[1].term}}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./turtle.y:125
		{
			yyVAL.predObj.pairs = append([]predicateObject{{Predicate: nil, Object: yyDollar[1].term}}, yyDollar[3].predObj.pairs...)
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./turtle.y:131
		{
			yyVAL.blankNodePO.node = IRI.RDF.Nil
			yyVAL.blankNodePO.triples = nil
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./turtle.y:135
		{
			triples := []interfaces.IQuad{}
			var head, prev interfaces.IBlankNode
			prev = yylex.(*lexer).newBlankNode()
			for i, item := range yyDollar[2].objectList {
				curr := prev
				quad, err := NewQuad(curr, IRI.RDF.First, item, NewDefaultGraph())
				if err != nil {
					yylex.(*lexer).Error(fmt.Sprintf("error constructing quad: %v", err))
					return 1
				}
				triples = append(triples, quad)

				var rest interfaces.ITerm
				if i == len(yyDollar[2].objectList)-1 {
					rest = IRI.RDF.Nil
				} else {
					rest = yylex.(*lexer).newBlankNode()
				}
				quad, err = NewQuad(curr, IRI.RDF.Rest, rest, NewDefaultGraph())
				if err != nil {
					yylex.(*lexer).Error(fmt.Sprintf("error constructing quad: %v", err))
					return 1
				}
				triples = append(triples, quad)

				if i == 0 {
					head = curr
				}
				prev = rest
			}
			yyVAL.blankNodePO.node = head
			yyVAL.blankNodePO.triples = triples
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:171
		{
			yyVAL.objectList = []interfaces.ITerm{yyDollar[1].term}
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./turtle.y:174
		{
			yyVAL.objectList = append([]interfaces.ITerm{yyDollar[1].term}, yyDollar[2].objectList...)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:179
		{
			yyVAL.term = yyDollar[1].term
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:180
		{
			yyVAL.term = NewBlankNode(yyDollar[1].str)
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:181
		{
			yyVAL.term = yyDollar[1].term
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:182
		{
			for _, q := range yyDollar[1].blankNodePO.triples {
				yylex.(*lexer).output <- q
			}
			yyVAL.term = yyDollar[1].blankNodePO.node
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:188
		{
			for _, q := range yyDollar[1].blankNodePO.triples {
				yylex.(*lexer).output <- q
			}
			yyVAL.term = yyDollar[1].blankNodePO.node
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:197
		{
			yyVAL.term = yyDollar[1].term
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:198
		{
			yyVAL.term = NewBlankNode(yyDollar[1].str)
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:199
		{
			yyVAL.term = yyDollar[1].term
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:200
		{
			yyVAL.term = yyDollar[1].literal
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:201
		{
			for _, q := range yyDollar[1].blankNodePO.triples {
				yylex.(*lexer).output <- q
			}
			yyVAL.term = yyDollar[1].blankNodePO.node
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:207
		{
			for _, q := range yyDollar[1].blankNodePO.triples {
				yylex.(*lexer).output <- q
			}
			yyVAL.term = yyDollar[1].blankNodePO.node
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:216
		{
			yyVAL.literal = NewLiteral("true", "", IRI.XSD.Boolean)
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:217
		{
			yyVAL.literal = NewLiteral("false", "", IRI.XSD.Boolean)
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:218
		{
			yyVAL.literal = NewLiteral(yyDollar[1].str, "", nil)
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./turtle.y:219
		{
			yyVAL.literal = NewLiteral(yyDollar[1].str, yyDollar[2].str, nil)
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./turtle.y:220
		{
			yyVAL.literal = NewLiteral(yyDollar[1].str, "", NewNamedNode(yyDollar[2].str))
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:221
		{
			yyVAL.literal = yyDollar[1].literal
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./turtle.y:225
		{
			yyVAL.blankNodePO.node = yylex.(*lexer).newBlankNode()
			yyVAL.blankNodePO.triples = nil
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./turtle.y:229
		{
			bnode := yylex.(*lexer).newBlankNode()
			var quads []interfaces.IQuad
			for _, po := range yyDollar[2].predObj.pairs {
				q, err := NewQuad(bnode, po.Predicate, po.Object, NewDefaultGraph())
				if err != nil {
					yylex.(*lexer).Error(fmt.Sprintf("blank node quad error: %v", err))
					return 1
				}
				quads = append(quads, q)
			}
			yyVAL.blankNodePO.node = bnode
			yyVAL.blankNodePO.triples = quads
		}
	case 44:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./turtle.y:245
		{
			prefix := yylex.(*lexer).prefixes[yyDollar[1].str]
			if prefix == "" {
				yylex.(*lexer).Error(fmt.Sprintf("prefix not found: %s", yyDollar[1].str))
				return 1
			}
			yyVAL.term = NewNamedNode(prefix + yyDollar[2].str)
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:253
		{
			prefix := yylex.(*lexer).prefixes[yyDollar[1].str]
			if prefix == "" {
				yylex.(*lexer).Error(fmt.Sprintf("prefix not found: %s", yyDollar[1].str))
				return 1
			}
			yyVAL.term = NewNamedNode(prefix)
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./turtle.y:264
		{
			if !strings.Contains(yyDollar[1].str, ":") && !strings.HasPrefix(yyDollar[1].str, "/") {
				base := yylex.(*lexer).base
				if base == "" {
					yylex.(*lexer).Error("@base not defined")
					return 1
				}
				yyVAL.term = NewNamedNode(base + yyDollar[1].str)
			} else {
				yyVAL.term = NewNamedNode(yyDollar[1].str)
			}
		}
	}
	goto yystack /* stack new state and value */
}
