name: "push"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Set up linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'v6.1.0'
          skip-cache: true

      - name: Run tests
        run: make pre-commit
