name: "push"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Set up linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          skip-cache: true

      - name: Run tests
        run: make pre-commit
